language: objective-c
compiler:
    - clang
branches:
    only:
        - master
notifications:
  recipients:
    - gxrtBk7MFiA26YqxA9PpXYxwEq6dkm@api.pushover.net
  email:
    on_success: always
    on_failure: always
install:
    - ./configure.sh
env:
    - BUILDTOOL=bjam BUILDMODE=debug
    - BUILDTOOL=bjam BUILDMODE=release
script: ./smoke_test.sh
